#! /bin/sh

findFilesChanged(){
    git diff --staged --name-only
}

findChanges(){
    read files

    egrep -n '[^A-Z0-9][A-Z0-9]{20}[^A-Z0-9]' "$files"
}

report(){
    read keys

    if [ -n "$keys" ]; then
        echo "AWS key found. Aborting commit."
        echo $keys
        exit 1
    else
        exit 0
    fi
}

findFilesChanged | findChanges | report
