#! /bin/sh

findFilesChanged(){
    git diff --staged --name-only
}

checkFiles(){
    read filesChanged

    if [[ $filesChanged == "i.do.not.have.keys.conf" ]]; then
        exit 0
    else
        echo "AWS key found. Aborting commit." 
        exit 1
    fi
}

findFilesChanged | checkFiles
